### ISSUE TITLE
remind: Certain characters break loading/parsing storage file

### ISSUE THREAD

**Issue by maxpowa** [sopel-irc/sopel#1055]
Messages containing tab, for one.

Remind could probably use some love too, maybe convert it over to use the database rather than the separate flatfile storage it uses now.

**Comment by dgw** [comment]
In another issue, @phixion reported the following:

> Adding this line as a reminder breaks remind.py:
>
> `( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ ^B^]^_ITS CARDBACK TIME!!!!!!!!!!!!!!!!!!!!!!!^B^]^_( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ`
>
> it breaks with:
>
> Error in remind setup procedure: need more than 1 value to unpack (modules/remind.py:38)

We'll consider that a duplicate of this, and expand the scope beyond just tab characters.

The few remaining modules that still use their own ".db" files (that aren't actually databases) really do need migrating to `bot.db`, and `remind` should be top of that list.

**Comment by Exirel** [comment]
I think I fixed the problem with tabs in #1581. I need to check that!

**Comment by dgw** [comment]
Was fixed by #1581; closing.

**Comment by dgw** [comment]
Some characters are still broken. Rather than reopen this issue (or create a new one), I instead decided to work on a patch. It'll be ready this weekend, guaranteed, for 7.0.1.
