### ISSUE TITLE
Reddit URLs result fail with errors.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1152]
I noticed this started happening recently in my Sopel v6.5.0:

```
BitchX showed:
...
[02:11am] <Ant>
          https://www.reddit.com/r/BritishTV/comments/5fbxqw/the_best_of_roy_and_moss_the_it_crowd/
02:11AM <URL> This setting can be provided in a praw.ini file, as a keyword argument to the
          `Reddit` class constructor, or as an environment variable. (file
          "/home/ant/SopelPython3/lib/python3.4/site-packages/praw/reddit.py", line 114, in
          __init__)
...
--

Terminal showed:

$ sopel -d
(SopelPython3)ant@mybox:~/$
Welcome to Sopel. Loading modules...


Error loading habitica: invalid syntax (common.py, line 25) (../sopel_modules/habitica/__init__.py:7)


Registered 46 modules,
1 modules failed to load


Connecting to irc.servername:6697...
Connected.
/home/ant/SopelPython3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/bot.py", line 470, in call
    exit_code = func(sopel, trigger)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/reddit.py", line 50, in rpost_info
    r = praw.Reddit(user_agent=USER_AGENT)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/praw/reddit.py", line 114, in __init__
    raise ClientException(required_message.format(attribute))
praw.exceptions.ClientException: Required configuration setting 'client_id' missing.
This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable.

ERROR:sopel.modules.sopel.irc:Exception from #linux: This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or as an environment variable. (file "/home/ant/SopelPython3/lib/python3.4/site-packages/praw/reddit.py", line 114, in __init__) (:Ant!~ant@<deleted address> PRIVMSG #linux :https://www.reddit.com/r/BritishTV/comments/5fbxqw/the_best_of_roy_and_moss_the_it_crowd/)
```

Thank you in advance. :)

**Comment by nfearnley** [comment]
I did some investigation. It looks like this is an issue with an API change between PRAW 3 and PRAW 4. The current reddit.py module supports PRAW 3, but does not support PRAW 4. At the moment, you can roll back your installed version of PRAW to PRAW 3, and you should be fine. In the future, it might be a good idea to consider updated reddit.py to support PRAW 4.

**Comment by nfearnley** [comment]
Another option would be to change requirements.txt from:

**Comment by antdude** [comment]
Also:

[DEFAULT]
# A boolean to indicate whether or not to check for package updates.
check_for_updates=True

# Object to kind mappings
comment_kind=t1
message_kind=t4
redditor_kind=t2
submission_kind=t3
subreddit_kind=t5

# The URL prefix for OAuth-related requests.
oauth_url=https://oauth.reddit.com

# The URL prefix for regular requests.
reddit_url=https://www.reddit.com

# The URL prefix for short URLs.
short_url=https://redd.it


I have no idea what to do with it.

**Comment by dgw** [comment]
Either Sopel's reddit module needs updating to use the new PRAW API, or the dependency needs pinning to a compatible version. I'll make sure the requirement is fixed for the next release, so Sopel will at least install alongside a usable PRAW version, and then I or someone else can handle a refactor of the module for a future update.

**Comment by dgw** [comment]
@kwaaak Is there significant benefit to requiring that fork instead of pinning the official PRAW at `<4.0` until rewriting the reddit module in Sopel 6.6? Current plan is to get 6.5.2 out ASAP (when `help` is fixed) and then go full-bore on feature updates for 6.6.0.

**Comment by kwaaak** [comment]
There was a time when the module broke because praw v3 was too old. I think the module was amended to account for that.
The praw fork I mentioned is being maintained, it is outlined in the beginning of the Readme.

I don't know if current praw will work without authentication. This could derail the planned rewrite.

**Comment by dgw** [comment]
Read-only PRAW instances are still allowed without logging in and without providing a client secret (tested with PRAW both 3.6.2 and 5.3.0). The planned rewrite might actually be unnecessary.

This issue appears to have been resolved as described in the OP, so I'll close it. The version of `reddit.py` that will be included in the next Sopel release actually needs PRAW >= 4.0.0 (I tested several PRAW versions on my instance), so the requirements will be updated to match.

**Comment by antdude** [comment]
I still see it:

[10:06am] <Ant> https://www.reddit.com/r/BritishTV/comments/5fbxqw/the_best_of_roy_and_moss_the_it_crowd/ test
10:06AM <URL> This setting can be provided in a praw.ini file, as a keyword argument to the `Reddit` class constructor, or
          as an environment variable. (file "/home/ant/SopelPython3/lib/python3.4/site-packages/praw/reddit.py", line 150,
          in __init__)
10:06AM <Crushinator> [REDDIT] The Best Of Roy And Moss - The IT Crowd  | 58 points () | 1 comments | Posted by MrDanWhite
          | Created at 2016-11-28T14:32:00+00:00

**Comment by dgw** [comment]
@antdude What version of PRAW is installed in your environment? I suspect it's 4.0 or above.

One option is to use the `reddit.py` from this repo as an override until the next version of Sopel is ready. It works with PRAW 4.0+. Or you can `pip install "praw<4.0"` (the quotes are required) and keep using the version of `reddit.py` included with Sopel 6.5.1 for now.

**Comment by antdude** [comment]
pip says prawcore-0.13.0. I tried your idea:

$ pip install "praw<4.0"
Collecting praw<4.0
  Downloading praw-3.6.2-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 2.1MB/s
Collecting decorator<4.1,>=4.0.9 (from praw<4.0)
  Downloading decorator-4.0.11-py2.py3-none-any.whl
Collecting six==1.10 (from praw<4.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.3.0 in /home/ant/SopelPython3/lib/python3.4/site-packages (from praw<4.0)
Requirement already satisfied: update-checker<1.0,>=0.12 in /home/ant/SopelPython3/lib/python3.4/site-packages (from praw<4.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests>=2.3.0->praw<4.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests>=2.3.0->praw<4.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests>=2.3.0->praw<4.0)
Requirement already satisfied: idna<2.7,>=2.5 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests>=2.3.0->praw<4.0)
Installing collected packages: decorator, six, praw
  Found existing installation: decorator 4.2.1
    Uninstalling decorator-4.2.1:
      Successfully uninstalled decorator-4.2.1
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: praw 5.3.0
    Uninstalling praw-5.3.0:
      Successfully uninstalled praw-5.3.0
Successfully installed decorator-4.0.11 praw-3.6.2 six-1.10.0



$ pip install "praw<4.0"
Requirement already satisfied: praw<4.0 in /home/ant/SopelPython3/lib/python3.4/site-packages
Requirement already satisfied: requests>=2.3.0 in /home/ant/SopelPython3/lib/python3.4/site-packages (from praw<4.0)
Requirement already satisfied: update-checker<1.0,>=0.12 in /home/ant/SopelPython3/lib/python3.4/site-packages (from praw<4.0)
Requirement already satisfied: decorator<4.1,>=4.0.9 in /home/ant/SopelPython3/lib/python3.4/site-packages (from praw<4.0)
Requirement already satisfied: six==1.10 in /home/ant/SopelPython3/lib/python3.4/site-packages (from praw<4.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests>=2.3.0->praw<4.0)
Requirement already satisfied: idna<2.7,>=2.5 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests>=2.3.0->praw<4.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests>=2.3.0->praw<4.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests>=2.3.0->praw<4.0)

Interesting:
$ pip list --outdated
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
decorator (4.0.11) - Latest: 4.2.1 [wheel]
praw (3.6.2) - Latest: 5.3.0 [wheel]
prawcore (0.13.0) - Latest: 0.14.0 [wheel]
six (1.10.0) - Latest: 1.11.0 [wheel]

$ pip install --upgrade decorator praw prawcore six
Collecting decorator
  Using cached decorator-4.2.1-py2.py3-none-any.whl
Collecting praw
  Using cached praw-5.3.0-py2.py3-none-any.whl
Collecting prawcore
  Using cached prawcore-0.14.0-py2.py3-none-any.whl
Collecting six
  Using cached six-1.11.0-py2.py3-none-any.whl
Requirement already up-to-date: update-checker>=0.16 in /home/ant/SopelPython3/lib/python3.4/site-packages (from praw)
Requirement already up-to-date: requests<3.0,>=2.6.0 in /home/ant/SopelPython3/lib/python3.4/site-packages (from prawcore)
Requirement already up-to-date: certifi>=2017.4.17 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests<3.0,>=2.6.0->prawcore)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests<3.0,>=2.6.0->prawcore)
Requirement already up-to-date: idna<2.7,>=2.5 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests<3.0,>=2.6.0->prawcore)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /home/ant/SopelPython3/lib/python3.4/site-packages (from requests<3.0,>=2.6.0->prawcore)
Installing collected packages: decorator, prawcore, praw, six
  Found existing installation: decorator 4.0.11
    Uninstalling decorator-4.0.11:
      Successfully uninstalled decorator-4.0.11
  Found existing installation: prawcore 0.13.0
    Uninstalling prawcore-0.13.0:
      Successfully uninstalled prawcore-0.13.0
  Found existing installation: praw 3.6.2
    Uninstalling praw-3.6.2:
      Successfully uninstalled praw-3.6.2
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
Successfully installed decorator-4.2.1 praw-5.3.0 prawcore-0.14.0 six-1.11.0

I retried it, and was able to reproduce it.

**Comment by dgw** [comment]
…

PRAW is _expected_ to be outdated if you use `pip install "praw<4.0"`. If you've just installed an old package version, why would you then immediately upgrade outdated packages? It puts PRAW 5.3.0 right back.

**Comment by antdude** [comment]
With the newer Python packages from pip instal --upgrade method, I decided to try https://raw.githubusercontent.com/sopel-irc/sopel/master/sopel/modules/reddit.py to overwrite my old one in /home/ant/SopelPython3/lib/python3.4/site-packages/praw/reddit.py. Restarted Sopel and retested:

[02:37pm] <Ant> https://www.reddit.com/r/CallOfDuty/comments/86vov0/my_dogs_reaction_to_my_mom_playing_call_of_duty/
02:37PM <URL> [ "My dogs reaction to my Mom playing Call of Duty WWII" [COD] : CallOfDuty ] - www.reddit.com

This works. Thanks. :)
